In [1]:
import numpy as np
n = 10
teta = np.random.rand(n)*2*np.pi
print(teta)
xy = np.array([250,250])
zipped = list(zip(np.cos(teta),np.sin(teta)))
zipped = np.dstack((np.cos(teta),np.sin(teta)))
print(zipped[0]+xy)
print(np.degrees(teta).reshape(10,1))
print(np.degrees(teta).reshape(10,1)[3])


[1.21154353 2.41806698 1.82810435 5.45397714 4.02104582 6.01252629
 3.05866655 2.66549604 4.43676661 4.75532518]
[[250.35157483 250.93615978]
 [249.25052371 250.66203119]
 [249.74552187 250.96707853]
 [250.67545987 249.26260325]
 [249.36242749 249.22960965]
 [250.96359491 249.73263348]
 [249.0034364  250.0828311 ]
 [249.11120934 250.45831338]
 [249.72785413 249.03774399]
 [250.04292301 249.00092162]]
[[ 69.41633096]
 [138.54503268]
 [104.74266383]
 [312.48987186]
 [230.38895489]
 [344.49238046]
 [175.24868402]
 [152.72167335]
 [254.2080014 ]
 [272.46006311]]
[312.48987186]


In [2]:
vec = [-1,0]
teta = np.arctan(vec[1]/vec[0])
print(np.degrees(teta))

-0.0


In [3]:
print(np.random.rand(10,2))

[[0.88517884 0.65239614]
 [0.82827924 0.75733564]
 [0.65907892 0.14193848]
 [0.7397207  0.68195543]
 [0.84751072 0.44924789]
 [0.64958194 0.08037477]
 [0.60998641 0.84020105]
 [0.47207693 0.16144822]
 [0.08277044 0.59507353]
 [0.41689285 0.25018297]]
